services:
  proxy-nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-nginx
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "81:81"      # Admin UI
      - "443:443"    # HTTPS
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./data/nginx-proxy-manager/data:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9100:9000"   # UI HTTP (externo 9100 para liberar 9000 a SonarQube)
      - "9443:9443"   # UI HTTPS (opcional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  portainer-data: