services:
  proxy-nginx:
    image: nginx:latest
    container_name: proxy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./static:/usr/share/nginx/html/static:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true